name: SecurityPipeline

on:
  push:
    branches: [ main ]

jobs:
  security_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Horusec Scan
        uses: ./.github/actions/horusec

      - name: SonarQube Scan
        uses: ./.github/actions/sonarqube
        with:
          projectKey: "mi-proyecto"
          host: "https://sonarcloud.io"
          token: ${{ secrets.SONAR_TOKEN }}

